name: Deploy to Workers Prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        run: sudo curl https://sh.rustup.rs -sSf | sh

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Install Wrangler
        run: sudo cargo install wrangler

      - name: Build
        run: hugo

      - name: config wrangler
        run: sudo CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish